export const conceptDeck = [
  // Original Easy Words (hardness: 1)
  { cardValue: "Baseball", hardness: 1 },
  { cardValue: "Milk", hardness: 1 },
  { cardValue: "Fish", hardness: 1 },
  { cardValue: "Pizza", hardness: 1 },
  { cardValue: "Lion", hardness: 1 },
  { cardValue: "Rainbow", hardness: 1 },
  { cardValue: "Television", hardness: 1 },
  { cardValue: "Ice Cream", hardness: 1 },
  { cardValue: "Beach", hardness: 1 },
  { cardValue: "Guitar", hardness: 1 },
  
  // Original Medium Words (hardness: 2)
  { cardValue: "Eiffel Tower", hardness: 2 },
  { cardValue: "Vincent van Gogh", hardness: 2 },
  { cardValue: "Leonardo DiCaprio", hardness: 2 },
  { cardValue: "Great Wall of China", hardness: 2 },
  { cardValue: "William Shakespeare", hardness: 2 },
  { cardValue: "Olympic Games", hardness: 2 },
  { cardValue: "Mona Lisa", hardness: 2 },
  { cardValue: "Ancient Egypt", hardness: 2 },
  { cardValue: "Mount Everest", hardness: 2 },
  { cardValue: "Albert Einstein", hardness: 2 },
  
  // Original Hard Words (hardness: 3)
  { cardValue: "Asterix and Obelix", hardness: 3 },
  { cardValue: "Industrial Revolution", hardness: 3 },
  { cardValue: "Climate Change", hardness: 3 },
  { cardValue: "Quantum Physics", hardness: 3 },
  { cardValue: "Evolution", hardness: 3 },
  { cardValue: "Democracy", hardness: 3 },
  { cardValue: "Renaissance", hardness: 3 },
  { cardValue: "Philosophy", hardness: 3 },

  // New Easy Words (hardness: 1)
  { cardValue: "Apple", hardness: 1 },
  { cardValue: "Airplane", hardness: 1 },
  { cardValue: "Baby", hardness: 1 },
  { cardValue: "Ball", hardness: 1 },
  { cardValue: "Banana", hardness: 1 },
  { cardValue: "Bed", hardness: 1 },
  { cardValue: "Bell", hardness: 1 },
  { cardValue: "Bird", hardness: 1 },
  { cardValue: "Book", hardness: 1 },
  { cardValue: "Bread", hardness: 1 },
  { cardValue: "Brush", hardness: 1 },
  { cardValue: "Bus", hardness: 1 },
  { cardValue: "Cake", hardness: 1 },
  { cardValue: "Camera", hardness: 1 },
  { cardValue: "Car", hardness: 1 },
  { cardValue: "Cat", hardness: 1 },
  { cardValue: "Chair", hardness: 1 },
  { cardValue: "Clock", hardness: 1 },
  { cardValue: "Cloud", hardness: 1 },
  { cardValue: "Computer", hardness: 1 },
  { cardValue: "Cookie", hardness: 1 },
  { cardValue: "Cup", hardness: 1 },
  { cardValue: "Dog", hardness: 1 },
  { cardValue: "Door", hardness: 1 },
  { cardValue: "Dress", hardness: 1 },
  { cardValue: "Drum", hardness: 1 },
  { cardValue: "Egg", hardness: 1 },
  { cardValue: "Elephant", hardness: 1 },
  { cardValue: "Eye", hardness: 1 },
  { cardValue: "Fire", hardness: 1 },
  { cardValue: "Flower", hardness: 1 },
  { cardValue: "Football", hardness: 1 },
  { cardValue: "Fork", hardness: 1 },
  { cardValue: "Frog", hardness: 1 },
  { cardValue: "Gift", hardness: 1 },
  { cardValue: "Glass", hardness: 1 },
  { cardValue: "Glove", hardness: 1 },
  { cardValue: "Hat", hardness: 1 },
  { cardValue: "Heart", hardness: 1 },
  { cardValue: "House", hardness: 1 },
  { cardValue: "Key", hardness: 1 },
  { cardValue: "Knife", hardness: 1 },
  { cardValue: "Lamp", hardness: 1 },
  { cardValue: "Leaf", hardness: 1 },
  { cardValue: "Lemon", hardness: 1 },
  { cardValue: "Letter", hardness: 1 },
  { cardValue: "Moon", hardness: 1 },
  { cardValue: "Mouse", hardness: 1 },
  { cardValue: "Mouth", hardness: 1 },
  { cardValue: "Nose", hardness: 1 },
  { cardValue: "Orange", hardness: 1 },
  { cardValue: "Pencil", hardness: 1 },
  { cardValue: "Phone", hardness: 1 },
  { cardValue: "Piano", hardness: 1 },
  { cardValue: "Picture", hardness: 1 },
  { cardValue: "Pig", hardness: 1 },
  { cardValue: "Pillow", hardness: 1 },
  { cardValue: "Plant", hardness: 1 },
  { cardValue: "Plate", hardness: 1 },
  { cardValue: "Rain", hardness: 1 },
  { cardValue: "Ring", hardness: 1 },
  { cardValue: "Robot", hardness: 1 },
  { cardValue: "Rock", hardness: 1 },
  { cardValue: "Rope", hardness: 1 },
  { cardValue: "Salt", hardness: 1 },
  { cardValue: "Sand", hardness: 1 },
  { cardValue: "School", hardness: 1 },
  { cardValue: "Scissors", hardness: 1 },
  { cardValue: "Ship", hardness: 1 },
  { cardValue: "Shoe", hardness: 1 },
  { cardValue: "Snake", hardness: 1 },
  { cardValue: "Snow", hardness: 1 },
  { cardValue: "Soap", hardness: 1 },
  { cardValue: "Sock", hardness: 1 },
  { cardValue: "Spoon", hardness: 1 },
  { cardValue: "Star", hardness: 1 },
  { cardValue: "Sun", hardness: 1 },
  { cardValue: "Table", hardness: 1 },
  { cardValue: "Tea", hardness: 1 },
  { cardValue: "Teeth", hardness: 1 },
  { cardValue: "Tiger", hardness: 1 },
  { cardValue: "Tomato", hardness: 1 },
  { cardValue: "Tooth", hardness: 1 },
  { cardValue: "Train", hardness: 1 },
  { cardValue: "Tree", hardness: 1 },
  { cardValue: "Truck", hardness: 1 },
  { cardValue: "Turtle", hardness: 1 },
  { cardValue: "Umbrella", hardness: 1 },
  { cardValue: "Wall", hardness: 1 },
  { cardValue: "Water", hardness: 1 },
  { cardValue: "Watch", hardness: 1 },
  { cardValue: "Wave", hardness: 1 },
  { cardValue: "Wedding", hardness: 1 },
  { cardValue: "Wheel", hardness: 1 },
  { cardValue: "Window", hardness: 1 },
  { cardValue: "Wing", hardness: 1 },
  { cardValue: "Winter", hardness: 1 },
  { cardValue: "Wood", hardness: 1 },
  { cardValue: "Worm", hardness: 1 },
  { cardValue: "Yogurt", hardness: 1 },
  { cardValue: "Zoo", hardness: 1 },
  { cardValue: "Doctor", hardness: 1 },
  { cardValue: "Teacher", hardness: 1 },
  { cardValue: "Chef", hardness: 1 },
  { cardValue: "Farmer", hardness: 1 },
  { cardValue: "Police", hardness: 1 }
];